#!/bin/sh
#!/bin/bash
#SBATCH --mail-user=bahtiyar.yilmaz@unibe.ch
#SBATCH --mail-type=end
#SBATCH --job-name="inStrainAll"
#SBATCH --nodes=1
#SBATCH --time=96:00:00
#SBATCH --mem-per-cpu=24G
#SBATCH --cpus-per-task=24
#SBATCH --partition=epyc2

##SBATCH --output=/path/to/outfile
##SBATCH --error=/path/to/errfile

#For array jobs
#Array job containing 10 tasks, run max 20 tasks at the same time
####SBATCH --array=1-4%4

#### Your shell commands below this line ####
#### Tutorial: https://github.com/bxlab/metaWRAP/blob/master/Usage_tutorial.md

source activate inStrain
cd /storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics
inStrain compare -i /storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1351.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1350.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1347.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1344.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1343.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1341.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1340.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1337.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1336.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1335.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1333.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1332.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1330.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1327.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1326.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1325.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1324.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1323.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1322.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1321.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1319.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1318.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1317.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1315.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1314.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1312.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1311.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1310.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1309.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1308.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W122.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W121.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W120.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W119.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W118.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W117.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W116.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W115.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W114.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W113.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W112.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W111.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W110.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W109.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W108.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W107.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W106.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W105.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W104.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W103.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W102.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W101.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W100.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W99.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W98.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W97.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W96.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W95.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W94.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W93.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W92.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W91.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W90.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W89.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W88.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W87.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W86.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W85.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W84.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W83.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W82.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W81.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W80.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W79.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W78.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W77.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W76.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W75.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W74.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W73.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W72.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W71.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W70.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W69.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W68.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W67.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W66.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W65.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W64.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W63.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W62.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W61.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W60.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W59.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W58.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W57.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W56.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W55.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W54.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W53.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W52.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W51.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W50.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W49.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W48.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W47.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W46.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W45.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W44.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W43.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W42.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W41.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W40.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W39.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W38.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W37.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W36.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W35.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W34.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W33.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W32.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W31.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W30.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W29.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W28.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W27.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W26.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W25.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W24.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W23.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W22.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W21.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W20.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W19.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W18.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W17.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W16.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W15.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W14.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W13.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W12.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W11.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W10.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W9.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W8.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W7.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W6.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W5.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W4.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W3.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W2.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/W1.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Sweden4.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Sweden3.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Sweden2.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Sweden1.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK18.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK17.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK16.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK10.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK9.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK8.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK7.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK6.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK5.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK4.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK3.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK2.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/SK1.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/RF4.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/RF3.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/RF2.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/RF1.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Poland4.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Poland3.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Poland2.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Poland1.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human16.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human15.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human14.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human13.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human12.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human11.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human10.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human9.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human8.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human7.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human6.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human5.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human2.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Human1.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Greece4.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Greece3.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Greece2.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Greece1.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Crick4.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Crick3.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Crick2.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Crick1.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H50.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H49.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H48.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H47.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H46.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H45.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H44.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H43.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H42.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H41.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H40.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H39.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H38.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H37.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H36.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H30.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H29.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H28.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H27.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H26.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H25.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H24.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H23.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H22.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H21.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H20.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H19.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H18.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H17.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H16.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H15.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H14.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H13.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H12.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H11.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H10.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H9.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H8.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H7.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H6.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H5.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H3.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H2.IS \
/storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/Bahti_H1.IS \
-s /storage/homefs/terziev/UHGGv1/UHGG_reps.stb \
-p 24 \
-o /storage/research/dbmr_yilmaz_gut_evo/Wild_Mice_Analysis/Metagenomics/Instrain/IS.COMPARE_All \
--database_mode
